name: Deployment pipeline

env:
  CONDITION: ${{ contains(join(toJson(github.event.commits.*.message), ','),'#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple-deployment-pipeline:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npx playwright install --with-deps
      - run: npm install
      - run: npm run eslint
      - run: npm run test
      - run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: 'Trigger Deployment'
        if: ${{ github.event_name == 'push' && env.CONDITION == 'false' }}
        run: curl https://api.render.com/deploy/srv-${{secrets.RENDER_SERVICE_ID}}?key=${{secrets.RENDER_API_KEY}}
  tag_release:
    needs: [simple-deployment-pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        if: ${{ github.event_name == 'push' && env.CONDITION == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  notify_discord:
    needs: [simple-deployment-pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v2.2.1
        if: success()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: AwesomeSauce GitHub Repo Build Process
          text: A new build was pushed to main
      - name: Test Fail
        uses: rjstone/discord-webhook-notify@v2.2.1
        if: failure()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: AwesomeSauce GitHub Repo Build Process
          text: A new build failed to pass tests
