name: Testing Context

on:
  push:
    branches:
      - testing-workflows

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: join and contains
        env:
          COMMIT_JOINED: ${{ contains(join(toJson(github.event.commits.*.message), ','),'#skip') }}
        run: echo "$COMMIT_JOINED"
      - name: putting in an if function
        if: ${{ contains(join(toJson(github.event.commits.*.message), ','),'#skip') }}
        run: echo 'Success1'
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v2.2.1
        if: success()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: AwesomeSauce GitHub Repo Build Process
          text: A new build was pushed to main
      - name: Test Fail
        uses: rjstone/discord-webhook-notify@v2.2.1
        if: failure()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: AwesomeSauce GitHub Repo Build Process
          text: A new build failed to pass tests
