name: Testing Context

on:
  push:
    branches:
      - testing-workflows

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: join and contains
        env:
          COMMIT_JOINED: ${{ contains(join(toJson(github.event.commits.*.message), ','),'#skip') }}
        run: echo "$COMMIT_JOINED"
      - name: putting in an if function
        if: ${{ contains(join(toJson(github.event.commits.*.message), ','),'#skip') }}
        run: echo 'Success1'

  notify_discord:
    runs-on: ubuntu-latest
    env:
      EMBED_STRING: '{"embeds": [{"title": "A new build on  {{ EVENT_PAYLOAD.repository.full_name }} is up.","description": "Check the repo for more info"}]}'
    steps:
      - uses: actions/checkout@v4
      - name: Test Success
        uses: Ilshidur/action-discord@master
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: ${{ toJson(env.EMBED_STRING) }}
        with:
          args: 'A new build on  {{ EVENT_PAYLOAD.repository.full_name }} is up.'
      - name: Test Fail
        uses: Ilshidur/action-discord@master
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'Failed to deploy to {{ EVENT_PAYLOAD.repository.full_name }}.'
